const services = {
  auth: {
    url: process.env.AUTH_SERVICE_URL || 'http://localhost:3010',
    name: 'Auth Service',
    routes: [
      '/api/login',
      '/api/userlogin',
      '/api/userexist',
      '/api/postuserportefeuille',
      '/api/forgot-password',
      '/api/reset-password',
      '/api/activate-user',
      '/api/users',
      '/api/getusersbyadmin',
    ],
  },
  funds: {
    url: process.env.FUND_SERVICE_URL || 'http://localhost:3011',
    name: 'Fund Service',
    routes: [
      '/api/postfond',
      '/api/updatefond',
      '/api/updatefondmodif',
      '/api/getfondbyadmin',
      '/api/getfondbyuser',
      '/api/getfondbyuservalide',
      '/api/getfondbysociete',
      '/api/getfondbypays',
      '/api/fondscharge',
      '/api/fonds',
      '/api/insertfond',
      '/api/getData',
      '/api/searchFunds',
      '/api/recherchefonds',
      '/api/rechercheravance-fonds',
      '/api/ajoutVL',
      '/api/ajoutIndice',
      '/api/uploadsfilevl',
      '/api/uploadsfileindice',
      '/api/uploadsocietefilenew',
      '/api/importfondsvl',
      '/api/verifvlimport',
      '/api/vlspresui',
      '/api/updateValues',
      '/api/getfondsanomalie',
      '/api/getallfondsvlanomalie',
      '/api/getallfondsvlmanquant',
      '/api/valLiq',
      '/api/doc',
      '/api/documents',
      '/api/documentsfond',
      '/api/frais',
      '/api/getfraisbyadmin',
      '/api/getfraisbyadminid',
      '/api/createfrais',
      '/api/updatefraisbyadminid',
      '/api/listeopcvm',
      '/api/listeproduit',
      '/api/comparaison',
    ],
  },
  performance: {
    url: process.env.PERFORMANCE_SERVICE_URL || 'http://localhost:3012',
    name: 'Performance Service',
    routes: [
      '/api/performancemonthyear',
      '/api/performanceindicemonthyear',
      '/api/performancescategorie',
      '/api/performancesdevcategorie',
      '/api/performancesindice',
      '/api/classementquartile',
      '/api/classementquartiledev',
      '/api/classementquartilemysql',
      '/api/calculatePerformance',
      '/api/ratiosportefeuille',
      '/api/ratiosportefeuilledev',
      '/api/ratiosportfeuillewithindice',
      '/api/rendement',
      '/api/performancesportefeuillewithindice',
    ],
  },
  portfolio: {
    url: process.env.PORTFOLIO_SERVICE_URL || 'http://localhost:3013',
    name: 'Portfolio Service',
    routes: [
      '/api/portefeuille',
      '/api/postportefeuille',
      '/api/updateportefeuille',
      '/api/getportefeuille',
      '/api/getportefeuillebyuser',
      '/api/assignportefeuille',
      '/api/portefeuillebase100',
      '/api/portefeuillebase100dev',
      '/api/portefeuillebase100s',
      '/api/valLiqportefeuille',
      '/api/valLiqportefeuilledev',
      '/api/valLiqportefeuillewithindice',
      '/api/valoriserportefeuille',
      '/api/createtransactions',
      '/api/gettransactions',
      '/api/managecash',
      '/api/vlpardate',
      '/api/changedevise',
      '/api/favorites',
      '/api/favoritesdata',
      '/api/favoritesdataall',
      '/api/saveValuationData',
      '/api/exportToExcel',
      '/api/usersWithFunds',
    ],
  },
  analytics: {
    url: process.env.ANALYTICS_SERVICE_URL || 'http://localhost:3014',
    name: 'Analytics Service',
    routes: [
      '/api/postsimulation',
      '/api/getsimulationbyuser',
      '/api/getsimulationportefeuillebyuser',
      '/api/getportefeuillebysimulation',
      '/api/robotadvisor',
      '/api/roboadvisorsetvalue',
      '/api/postportefeuillepropose',
      '/api/reconstitution',
      '/api/searchFundsreconstitution',
      '/api/reportingmensuelle',
      '/api/generate-excel-report',
      '/api/telechargerword',
      '/api/wordexemple',
      '/api/fill-template',
    ],
  },
  reference: {
    url: process.env.REFERENCE_SERVICE_URL || 'http://localhost:3015',
    name: 'Reference Service',
    routes: [
      '/api/getPays',
      '/api/getPaysall',
      '/api/getRegulateur',
      '/api/getDevise',
      '/api/getDevises',
      '/api/getCategories',
      '/api/getIndice',
      '/api/getSocietes',
      '/api/getSocietesbypays',
      '/api/getSocietebyid',
      '/api/addSociete',
      '/api/updateSociete',
      '/api/getCompaniesInCountry',
      '/api/tsr',
      '/api/fetch-currency-pairs',
      '/api/listesociete',
      '/api/listesocietepays',
    ],
  },
  notification: {
    url: process.env.NOTIFICATION_SERVICE_URL || 'http://localhost:3016',
    name: 'Notification Service',
    routes: [
      '/api/actualite',
      '/api/getactualite',
      '/api/contact',
      '/api/personnelsociete',
      '/api/personnelsocietemodif',
      '/api/personnelsocietecharge',
      '/api/personnel',
      '/api/generate-api-key',
      '/api/renew-api-key',
      '/api/api-keys',
    ],
  },
};

module.exports = services;
