CREATE TABLE IF NOT EXISTS performences (id Int32, fond Nullable(String), fond_id Int32, date Date, code_ISIN Nullable(String), categorie Nullable(String), devise Nullable(String), categorie_nationale Nullable(String), categorie_regionale Nullable(String), anomalie Nullable(String), ytd Nullable(String), perfveille Nullable(String), perf1an Nullable(String), perf3ans Nullable(String), perf5ans Nullable(String), perf8ans Nullable(String), perf10ans Nullable(String), perf4s Nullable(String), perf3m Nullable(String), perf6m Nullable(String), ytdm Nullable(String), perfveillem Nullable(String), perf1anm Nullable(String), perf3ansm Nullable(String), perf5ansm Nullable(String), perf8ansm Nullable(String), perf10ansm Nullable(String), perf4sm Nullable(String), perf3mm Nullable(String), perf6mm Nullable(String), perfannu1an Nullable(String), volatility1an Nullable(String), ratiosharpe1an Nullable(String), pertemax1an Nullable(String), sortino1an Nullable(String), omega1an Nullable(String), dsr1an Nullable(String), downcapture1an Nullable(String), upcapture1an Nullable(String), skewness1an Nullable(String), kurtosis1an Nullable(String), info1an Nullable(String), calamar1an Nullable(String), var991an Nullable(String), var951an Nullable(String), trackingerror1an Nullable(String), betahaussier1an Nullable(String), betabaissier1an Nullable(String), beta1an Nullable(String), perfannu3an Nullable(String), volatility3an Nullable(String), ratiosharpe3an Nullable(String), pertemax3an Nullable(String), sortino3an Nullable(String), omega3an Nullable(String), dsr3an Nullable(String), downcapture3an Nullable(String), upcapture3an Nullable(String), skewness3an Nullable(String), kurtosis3an Nullable(String), info3an Nullable(String), calamar3an Nullable(String), var993an Nullable(String), var953an Nullable(String), trackingerror3an Nullable(String), betahaussier3an Nullable(String), betabaissier3an Nullable(String), beta3an Nullable(String), perfannu5an Nullable(String), volatility5an Nullable(String), ratiosharpe5an Nullable(String), pertemax5an Nullable(String), sortino5an Nullable(String), omega5an Nullable(String), dsr5an Nullable(String), downcapture5an Nullable(String), upcapture5an Nullable(String), skewness5an Nullable(String), kurtosis5an Nullable(String), info5an Nullable(String), calamar5an Nullable(String), var995an Nullable(String), var955an Nullable(String), trackingerror5an Nullable(String), betahaussier5an Nullable(String), betabaissier5an Nullable(String), beta5an Nullable(String)) ENGINE = MergeTree() ORDER BY date;



clickhouse-client --user=default --password="Testing" --query="CREATE TABLE IF NOT EXISTS performences (id Int32, fond String DEFAULT NULL, fond_id Int32 DEFAULT NULL, date Date DEFAULT NULL, code_ISIN String DEFAULT NULL, categorie String DEFAULT NULL, devise String DEFAULT NULL, categorie_nationale String DEFAULT NULL, categorie_regionale String DEFAULT NULL, anomalie String DEFAULT NULL, ytd String DEFAULT NULL, perfveille String DEFAULT NULL, perf1an String DEFAULT NULL, perf3ans String DEFAULT NULL, perf5ans String DEFAULT NULL, perf8ans Float64 DEFAULT NULL, perf10ans Float64 DEFAULT NULL, perf4s String DEFAULT NULL, perf3m String DEFAULT NULL, perf6m String DEFAULT NULL, ytdm String DEFAULT NULL, perfveillem String DEFAULT NULL, perf1anm String DEFAULT NULL, perf3ansm String DEFAULT NULL, perf5ansm String DEFAULT NULL, perf8ansm String DEFAULT NULL, perf10ansm String DEFAULT NULL, perf4sm String DEFAULT NULL, perf3mm String DEFAULT NULL, perf6mm String DEFAULT NULL, perfannu1an String DEFAULT NULL, volatility1an String DEFAULT NULL, ratiosharpe1an String DEFAULT NULL, pertemax1an String DEFAULT NULL, sortino1an String DEFAULT NULL, omega1an String DEFAULT NULL, dsr1an String DEFAULT NULL, downcapture1an String DEFAULT NULL, upcapture1an String DEFAULT NULL, skewness1an String DEFAULT NULL, kurtosis1an String DEFAULT NULL, info1an String DEFAULT NULL, calamar1an String DEFAULT NULL, var991an String DEFAULT NULL, var951an String DEFAULT NULL, trackingerror1an String DEFAULT NULL, betahaussier1an String DEFAULT NULL, betabaissier1an String DEFAULT NULL, beta1an String DEFAULT NULL, perfannu3an String DEFAULT NULL, volatility3an String DEFAULT NULL, ratiosharpe3an String DEFAULT NULL, pertemax3an String DEFAULT NULL, sortino3an String DEFAULT NULL, omega3an String DEFAULT NULL, dsr3an String DEFAULT NULL, downcapture3an String DEFAULT NULL, upcapture3an String DEFAULT NULL, skewness3an String DEFAULT NULL, kurtosis3an String DEFAULT NULL, info3an String DEFAULT NULL, calamar3an String DEFAULT NULL, var993an String DEFAULT NULL, var953an String DEFAULT NULL, trackingerror3an String DEFAULT NULL, betahaussier3an String DEFAULT NULL, betabaissier3an String DEFAULT NULL, beta3an String DEFAULT NULL, perfannu5an String DEFAULT NULL, volatility5an String DEFAULT NULL, ratiosharpe5an String DEFAULT NULL, pertemax5an String DEFAULT NULL, sortino5an String DEFAULT NULL, omega5an String DEFAULT NULL, dsr5an String DEFAULT NULL, downcapture5an String DEFAULT NULL, upcapture5an String DEFAULT NULL, skewness5an String DEFAULT NULL, kurtosis5an String DEFAULT NULL, info5an String DEFAULT NULL, calamar5an String DEFAULT NULL, var995an String DEFAULT NULL, var955an String DEFAULT NULL, trackingerror5an String DEFAULT NULL, betahaussier5an String DEFAULT NULL, betabaissier5an String DEFAULT NULL, beta5an String DEFAULT NULL) ENGINE = MergeTree() ORDER BY id;"

CREATE TABLE IF NOT EXISTS classementfonds (fond_id UInt32, categorie_nationale Nullable(String), type_classement UInt8, categorie_regionale Nullable(String), categorie Nullable(String), rank3Mois Nullable(String), rank6Mois Nullable(String), rank1An Nullable(String), rank3Ans Nullable(String), rank5Ans Nullable(String), rank1erJanvier Nullable(String), rank3Moistotal Nullable(String), rank6Moistotal Nullable(String), rank1Antotal Nullable(String), rank3Anstotal Nullable(String), rank5Anstotal Nullable(String), rank1erJanviertotal Nullable(String), rankvolatilite Nullable(String), ranksharpe Nullable(String), rankcalamar Nullable(String), rankomega Nullable(String), rankdsr Nullable(String), ranksortino Nullable(String), rankvar95 Nullable(String), rankbetabaissier Nullable(String), rankinfo Nullable(String), rankpertemax Nullable(String), rankvolatilitetotal Nullable(String), ranksharpetotal Nullable(String), rankcalamartotal Nullable(String), rankomegatotal Nullable(String), rankdsrtotal Nullable(String), ranksortinototal Nullable(String), rankvar95total Nullable(String), rankbetabaissiertotal Nullable(String), rankinfototal Nullable(String), rankpertemaxtotal Nullable(String)) ENGINE = MergeTree() ORDER BY fond_id;



/////


ALTER TABLE `fond_investissements` ADD `nombre_part` INT NULL AFTER `dividende`;
ALTER TABLE `fond_investissements` ADD `banque` VARCHAR(255) NULL AFTER `nombre_part`, ADD `IBAN` VARCHAR(255) NULL AFTER `banque`, ADD `RIB` VARCHAR(255) NULL AFTER `IBAN`;
ALTER TABLE `fond_investissements` CHANGE `depositaire` `depositaire` VARCHAR(255) NULL DEFAULT NULL, CHANGE `teneur_registre` `teneur_registre` VARCHAR(255) NULL DEFAULT NULL, CHANGE `valorisateur` `valorisateur` VARCHAR(255) NULL DEFAULT NULL, CHANGE `centralisateur` `centralisateur` VARCHAR(255) NULL DEFAULT NULL, CHANGE `agent_transfert` `agent_transfert` VARCHAR(255) NULL DEFAULT NULL, CHANGE `agent_payeur` `agent_payeur` VARCHAR(255) NULL DEFAULT NULL;
